/** @type {import('tailwindcss').Config} */

// Every colour resolves through a CSS variable, so a single data-theme stamp on
// <html> reflows the entire palette. Class names in the app never change - the
// 5,012 places that already say bg-slate-50 or text-slate-900 simply start
// reading a variable. Nothing about spacing, size or layout is involved.
//
// The ramps live in src/index.css. Light values are Tailwind's own, so light
// mode is pixel-identical to before this landed.
const token = (name) => `rgb(var(--${name}) / <alpha-value>)`;

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
      slate: {
        50: "rgb(var(--c-slate-50) / <alpha-value>)",
        100: "rgb(var(--c-slate-100) / <alpha-value>)",
        200: "rgb(var(--c-slate-200) / <alpha-value>)",
        300: "rgb(var(--c-slate-300) / <alpha-value>)",
        400: "rgb(var(--c-slate-400) / <alpha-value>)",
        500: "rgb(var(--c-slate-500) / <alpha-value>)",
        600: "rgb(var(--c-slate-600) / <alpha-value>)",
        700: "rgb(var(--c-slate-700) / <alpha-value>)",
        800: "rgb(var(--c-slate-800) / <alpha-value>)",
        900: "rgb(var(--c-slate-900) / <alpha-value>)",
      },
      gray: {
        50: "rgb(var(--c-gray-50) / <alpha-value>)",
        100: "rgb(var(--c-gray-100) / <alpha-value>)",
        200: "rgb(var(--c-gray-200) / <alpha-value>)",
        300: "rgb(var(--c-gray-300) / <alpha-value>)",
        400: "rgb(var(--c-gray-400) / <alpha-value>)",
        500: "rgb(var(--c-gray-500) / <alpha-value>)",
        600: "rgb(var(--c-gray-600) / <alpha-value>)",
        700: "rgb(var(--c-gray-700) / <alpha-value>)",
        800: "rgb(var(--c-gray-800) / <alpha-value>)",
        900: "rgb(var(--c-gray-900) / <alpha-value>)",
      },
      red: {
        50: "rgb(var(--c-red-50) / <alpha-value>)",
        100: "rgb(var(--c-red-100) / <alpha-value>)",
        200: "rgb(var(--c-red-200) / <alpha-value>)",
        300: "rgb(var(--c-red-300) / <alpha-value>)",
        400: "rgb(var(--c-red-400) / <alpha-value>)",
        500: "rgb(var(--c-red-500) / <alpha-value>)",
        600: "rgb(var(--c-red-600) / <alpha-value>)",
        700: "rgb(var(--c-red-700) / <alpha-value>)",
        800: "rgb(var(--c-red-800) / <alpha-value>)",
        900: "rgb(var(--c-red-900) / <alpha-value>)",
      },
      orange: {
        50: "rgb(var(--c-orange-50) / <alpha-value>)",
        100: "rgb(var(--c-orange-100) / <alpha-value>)",
        200: "rgb(var(--c-orange-200) / <alpha-value>)",
        300: "rgb(var(--c-orange-300) / <alpha-value>)",
        400: "rgb(var(--c-orange-400) / <alpha-value>)",
        500: "rgb(var(--c-orange-500) / <alpha-value>)",
        600: "rgb(var(--c-orange-600) / <alpha-value>)",
        700: "rgb(var(--c-orange-700) / <alpha-value>)",
        800: "rgb(var(--c-orange-800) / <alpha-value>)",
        900: "rgb(var(--c-orange-900) / <alpha-value>)",
      },
      amber: {
        50: "rgb(var(--c-amber-50) / <alpha-value>)",
        100: "rgb(var(--c-amber-100) / <alpha-value>)",
        200: "rgb(var(--c-amber-200) / <alpha-value>)",
        300: "rgb(var(--c-amber-300) / <alpha-value>)",
        400: "rgb(var(--c-amber-400) / <alpha-value>)",
        500: "rgb(var(--c-amber-500) / <alpha-value>)",
        600: "rgb(var(--c-amber-600) / <alpha-value>)",
        700: "rgb(var(--c-amber-700) / <alpha-value>)",
        800: "rgb(var(--c-amber-800) / <alpha-value>)",
        900: "rgb(var(--c-amber-900) / <alpha-value>)",
      },
      yellow: {
        50: "rgb(var(--c-yellow-50) / <alpha-value>)",
        100: "rgb(var(--c-yellow-100) / <alpha-value>)",
        200: "rgb(var(--c-yellow-200) / <alpha-value>)",
        300: "rgb(var(--c-yellow-300) / <alpha-value>)",
        400: "rgb(var(--c-yellow-400) / <alpha-value>)",
        500: "rgb(var(--c-yellow-500) / <alpha-value>)",
        600: "rgb(var(--c-yellow-600) / <alpha-value>)",
        700: "rgb(var(--c-yellow-700) / <alpha-value>)",
        800: "rgb(var(--c-yellow-800) / <alpha-value>)",
        900: "rgb(var(--c-yellow-900) / <alpha-value>)",
      },
      green: {
        50: "rgb(var(--c-green-50) / <alpha-value>)",
        100: "rgb(var(--c-green-100) / <alpha-value>)",
        200: "rgb(var(--c-green-200) / <alpha-value>)",
        300: "rgb(var(--c-green-300) / <alpha-value>)",
        400: "rgb(var(--c-green-400) / <alpha-value>)",
        500: "rgb(var(--c-green-500) / <alpha-value>)",
        600: "rgb(var(--c-green-600) / <alpha-value>)",
        700: "rgb(var(--c-green-700) / <alpha-value>)",
        800: "rgb(var(--c-green-800) / <alpha-value>)",
        900: "rgb(var(--c-green-900) / <alpha-value>)",
      },
      emerald: {
        50: "rgb(var(--c-emerald-50) / <alpha-value>)",
        100: "rgb(var(--c-emerald-100) / <alpha-value>)",
        200: "rgb(var(--c-emerald-200) / <alpha-value>)",
        300: "rgb(var(--c-emerald-300) / <alpha-value>)",
        400: "rgb(var(--c-emerald-400) / <alpha-value>)",
        500: "rgb(var(--c-emerald-500) / <alpha-value>)",
        600: "rgb(var(--c-emerald-600) / <alpha-value>)",
        700: "rgb(var(--c-emerald-700) / <alpha-value>)",
        800: "rgb(var(--c-emerald-800) / <alpha-value>)",
        900: "rgb(var(--c-emerald-900) / <alpha-value>)",
      },
      cyan: {
        50: "rgb(var(--c-cyan-50) / <alpha-value>)",
        100: "rgb(var(--c-cyan-100) / <alpha-value>)",
        200: "rgb(var(--c-cyan-200) / <alpha-value>)",
        300: "rgb(var(--c-cyan-300) / <alpha-value>)",
        400: "rgb(var(--c-cyan-400) / <alpha-value>)",
        500: "rgb(var(--c-cyan-500) / <alpha-value>)",
        600: "rgb(var(--c-cyan-600) / <alpha-value>)",
        700: "rgb(var(--c-cyan-700) / <alpha-value>)",
        800: "rgb(var(--c-cyan-800) / <alpha-value>)",
        900: "rgb(var(--c-cyan-900) / <alpha-value>)",
      },
      blue: {
        50: "rgb(var(--c-blue-50) / <alpha-value>)",
        100: "rgb(var(--c-blue-100) / <alpha-value>)",
        200: "rgb(var(--c-blue-200) / <alpha-value>)",
        300: "rgb(var(--c-blue-300) / <alpha-value>)",
        400: "rgb(var(--c-blue-400) / <alpha-value>)",
        500: "rgb(var(--c-blue-500) / <alpha-value>)",
        600: "rgb(var(--c-blue-600) / <alpha-value>)",
        700: "rgb(var(--c-blue-700) / <alpha-value>)",
        800: "rgb(var(--c-blue-800) / <alpha-value>)",
        900: "rgb(var(--c-blue-900) / <alpha-value>)",
      },
      indigo: {
        50: "rgb(var(--c-indigo-50) / <alpha-value>)",
        100: "rgb(var(--c-indigo-100) / <alpha-value>)",
        200: "rgb(var(--c-indigo-200) / <alpha-value>)",
        300: "rgb(var(--c-indigo-300) / <alpha-value>)",
        400: "rgb(var(--c-indigo-400) / <alpha-value>)",
        500: "rgb(var(--c-indigo-500) / <alpha-value>)",
        600: "rgb(var(--c-indigo-600) / <alpha-value>)",
        700: "rgb(var(--c-indigo-700) / <alpha-value>)",
        800: "rgb(var(--c-indigo-800) / <alpha-value>)",
        900: "rgb(var(--c-indigo-900) / <alpha-value>)",
      },
      violet: {
        50: "rgb(var(--c-violet-50) / <alpha-value>)",
        100: "rgb(var(--c-violet-100) / <alpha-value>)",
        200: "rgb(var(--c-violet-200) / <alpha-value>)",
        300: "rgb(var(--c-violet-300) / <alpha-value>)",
        400: "rgb(var(--c-violet-400) / <alpha-value>)",
        500: "rgb(var(--c-violet-500) / <alpha-value>)",
        600: "rgb(var(--c-violet-600) / <alpha-value>)",
        700: "rgb(var(--c-violet-700) / <alpha-value>)",
        800: "rgb(var(--c-violet-800) / <alpha-value>)",
        900: "rgb(var(--c-violet-900) / <alpha-value>)",
      },
      purple: {
        50: "rgb(var(--c-purple-50) / <alpha-value>)",
        100: "rgb(var(--c-purple-100) / <alpha-value>)",
        200: "rgb(var(--c-purple-200) / <alpha-value>)",
        300: "rgb(var(--c-purple-300) / <alpha-value>)",
        400: "rgb(var(--c-purple-400) / <alpha-value>)",
        500: "rgb(var(--c-purple-500) / <alpha-value>)",
        600: "rgb(var(--c-purple-600) / <alpha-value>)",
        700: "rgb(var(--c-purple-700) / <alpha-value>)",
        800: "rgb(var(--c-purple-800) / <alpha-value>)",
        900: "rgb(var(--c-purple-900) / <alpha-value>)",
      },
      rose: {
        50: "rgb(var(--c-rose-50) / <alpha-value>)",
        100: "rgb(var(--c-rose-100) / <alpha-value>)",
        200: "rgb(var(--c-rose-200) / <alpha-value>)",
        300: "rgb(var(--c-rose-300) / <alpha-value>)",
        400: "rgb(var(--c-rose-400) / <alpha-value>)",
        500: "rgb(var(--c-rose-500) / <alpha-value>)",
        600: "rgb(var(--c-rose-600) / <alpha-value>)",
        700: "rgb(var(--c-rose-700) / <alpha-value>)",
        800: "rgb(var(--c-rose-800) / <alpha-value>)",
        900: "rgb(var(--c-rose-900) / <alpha-value>)",
      },

        // Semantic tokens, shared with the super-admin panel.
        bg: token("bg"),
        surface: token("surface"),
        "surface-2": token("surface-2"),
        "surface-3": token("surface-3"),
        border: token("border"),
        "border-strong": token("border-strong"),

        text: token("text"),
        "text-muted": token("text-muted"),
        "text-subtle": token("text-subtle"),

        accent: token("accent"),
        "accent-hover": token("accent-hover"),
        "accent-soft": token("accent-soft"),
        "accent-fg": token("accent-fg"),

        success: token("success"),
        "success-soft": token("success-soft"),
        warning: token("warning"),
        "warning-soft": token("warning-soft"),
        danger: token("danger"),
        "danger-soft": token("danger-soft"),
        info: token("info"),
        "info-soft": token("info-soft"),

        "series-1": token("series-1"),
        "series-2": token("series-2"),
        "series-3": token("series-3"),
        "series-4": token("series-4"),
        grid: token("grid"),
      },

      // bg-white means "a raised card" in 271 places, so it follows the theme.
      backgroundColor: ({ theme }) => ({
        ...theme("colors"),
        white: token("c-surface"),
      }),

      // text-white sits on blue and red buttons. It must stay literally white,
      // and keying textColor separately is what makes that possible.
      textColor: ({ theme }) => ({
        ...theme("colors"),
        white: "#ffffff",
      }),

      keyframes: {
        shimmer: { "100%": { transform: "translateX(100%)" } },
      },
      animation: {
        shimmer: "shimmer 1.6s infinite",
      },
      boxShadow: {
        card: "var(--shadow-sm)",
        raised: "var(--shadow-md)",
        overlay: "var(--shadow-lg)",
      },
    },
  },
  plugins: [],
};
