import { useState } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import Card from "../common/Card";
import Table from "../common/Table";
import { formatCurrency } from "../../utils/formatters";
import { axisProps, gridProps, tooltipProps, seriesColor, BAR_RADIUS } from "../../utils/chartTheme";

export default function CashierBranchComparisonView({ cashierData, branchData }) {
  const [tab,setTab]=useState("cashiers");
  const rows=tab==="cashiers"?(cashierData||[]):(branchData||[]);
  const chart=rows.slice(0,10).map(r=>({name:(r.cashierUsername||r.branchName||"").slice(0,16),sales:Number(r.totalSales||0)}));
  const totalSales=rows.reduce((s,r)=>s+Number(r.totalSales||0),0);
  return <div className="space-y-6"><div className="flex gap-2"><button onClick={()=>setTab("cashiers")} className={`min-h-11 rounded-full px-4 py-2 text-sm font-bold ${tab==="cashiers"?"bg-blue-600 text-white":"bg-slate-100"}`}>Cashiers</button><button onClick={()=>setTab("branches")} className={`min-h-11 rounded-full px-4 py-2 text-sm font-bold ${tab==="branches"?"bg-blue-600 text-white":"bg-slate-100"}`}>Branches</button></div>
  <div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><div className="rounded-xl border p-4"><p className="text-xs font-bold uppercase text-slate-500">Total Sales</p><p className="mt-2 text-xl font-black text-blue-700">{formatCurrency(totalSales)}</p></div><div className="rounded-xl border p-4"><p className="text-xs font-bold uppercase text-slate-500">{tab==="cashiers"?"Cashiers":"Branches"}</p><p className="mt-2 text-xl font-black">{rows.length}</p></div><div className="rounded-xl border p-4"><p className="text-xs font-bold uppercase text-slate-500">Top Performer</p><p className="mt-2 truncate text-xl font-black">{rows[0]?.cashierUsername||rows[0]?.branchName||"-"}</p></div></div>
  <Card className="admin-panel-card p-5"><h2 className="text-lg font-black">Sales Comparison</h2><div className="mt-4 h-[280px] min-h-[280px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid {...gridProps}/><XAxis dataKey="name" {...axisProps} tick={{...axisProps.tick,fontSize:10}}/><YAxis tickFormatter={v=>`${Math.round(v/1000)}K`} {...axisProps}/><Tooltip formatter={v=>[formatCurrency(v),"Sales"]} {...tooltipProps}/><Bar dataKey="sales" fill={seriesColor(0)} radius={BAR_RADIUS}/></BarChart></ResponsiveContainer></div></Card>
  <Card className="admin-panel-card overflow-hidden p-0" title={tab==="cashiers"?"Cashier Performance":"Branch Comparison"}><div className="space-y-3 p-4 md:hidden">{rows.map(r=><div key={r.cashierUserId||r.branchId} className="rounded-xl border p-4"><p className="font-black">{r.cashierUsername||r.branchName}</p><p className="mt-2 text-lg font-bold text-blue-700">{formatCurrency(r.totalSales)}</p><p className="text-xs text-slate-500">{r.orderCount} orders · Avg {formatCurrency(r.avgOrderValue??r.averageOrderValue)}</p></div>)}</div><div className="hidden md:block"><Table columns={tab==="cashiers"?[{header:"Cashier",accessor:"cashierUsername"},{header:"Orders",accessor:"orderCount"},{header:"Sales",render:r=>formatCurrency(r.totalSales)},{header:"Avg Order",render:r=>formatCurrency(r.avgOrderValue)},{header:"Discounts",render:r=>formatCurrency(r.totalDiscounts)},{header:"Returns",accessor:"returnCount"},{header:"Refunds",render:r=>formatCurrency(r.totalRefunds)}]:[{header:"Branch",accessor:"branchName"},{header:"Orders",accessor:"orderCount"},{header:"Sales",render:r=>formatCurrency(r.totalSales)},{header:"Avg Order",render:r=>formatCurrency(r.averageOrderValue)},{header:"Discounts",render:r=>formatCurrency(r.totalDiscounts)},{header:"Returns",accessor:"returnCount"},{header:"Return Amount",render:r=>formatCurrency(r.returnAmount)},{header:"Expenses",render:r=>formatCurrency(r.operatingExpenses)}]} data={rows}/></div></Card></div>;
}
