import { useMemo, useState } from "react";
import { BarChart3, DollarSign, Package, TrendingUp } from "lucide-react";
import { Bar, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import Card from "../common/Card";
import Table from "../common/Table";
import { formatCurrency } from "../../utils/formatters";

const filters = [{ id: "ALL", label: "All" }, { id: "NEGATIVE", label: "Loss Making" }, { id: "LOW", label: "Margin ≤ 10%" }, { id: "MISSING", label: "Missing Cost" }];
const qty = (value, unit) => `${Number(value || 0).toLocaleString(undefined, { maximumFractionDigits: 3 })} ${unit || ""}`.trim();
const compactProductName = (value) => {
  const name = String(value || "Unknown product");
  return name.length > 16 ? `${name.slice(0, 15)}…` : name;
};

export default function ProductCategoryIntelligenceView({ data, intelligenceData, totalElements }) {
  const rows = useMemo(() => Array.isArray(data) ? data : [], [data]);
  const intelligenceRows = useMemo(() => Array.isArray(intelligenceData) && intelligenceData.length ? intelligenceData : rows, [intelligenceData, rows]);
  const [filter, setFilter] = useState("ALL");
  const filtered = useMemo(() => rows.filter((r) => filter === "ALL" || (filter === "NEGATIVE" && Number(r.profit) < 0) || (filter === "LOW" && Number(r.marginPercent) >= 0 && Number(r.marginPercent) <= 10) || (filter === "MISSING" && Number(r.revenue) > 0 && Number(r.cost) <= 0)), [rows, filter]);
  const totals = intelligenceRows.reduce((s, r) => ({ revenue: s.revenue + Number(r.revenue || 0), cost: s.cost + Number(r.cost || 0), profit: s.profit + Number(r.profit || 0) }), { revenue: 0, cost: 0, profit: 0 });
  let cumulative = 0;
  const pareto = [...intelligenceRows].sort((a, b) => Number(b.revenue) - Number(a.revenue)).slice(0, 10).map((r) => { cumulative += Number(r.revenue || 0); return { name: r.itemName || "Unknown product", revenue: Number(r.revenue || 0), cumulative: totals.revenue ? cumulative / totals.revenue * 100 : 0 }; });
  const coverage = Number(totalElements || 0) > intelligenceRows.length ? `Top ${intelligenceRows.length} products` : "All products in period";
  const missingCostCount = intelligenceRows.filter((row) => Number(row.revenue || 0) > 0 && Number(row.cost || 0) <= 0).length;
  const metrics = [["Product Revenue", totals.revenue, `${coverage}; before bill discounts`, DollarSign, "text-blue-700"], ["Gross Profit", totals.profit, `${coverage}; stored line cost`, TrendingUp, "text-emerald-700"], ["Gross Margin", totals.revenue ? totals.profit / totals.revenue * 100 : 0, coverage, BarChart3, "text-indigo-700"], ["Products", totalElements || rows.length, `${rows.length} shown on this page`, Package, "text-amber-700"]];
  return <div className="space-y-6">
    {missingCostCount > 0 && <div className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900"><p className="font-black">Product profit confidence warning</p><p className="mt-1">{missingCostCount} of the {intelligenceRows.length} products in this intelligence set have revenue but no recorded cost. Product profit and margin may be overstated.</p></div>}
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([title, value, helper, Icon, tone], i) => <div key={title} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase text-slate-500">{title}</p><p className={`mt-2 text-xl font-black ${tone}`}>{i === 2 ? `${Number(value).toFixed(1)}%` : i === 3 ? Number(value).toLocaleString() : formatCurrency(value)}</p><p className="mt-1 text-xs font-semibold text-slate-500">{helper}</p></div><Icon size={20} className={tone} /></div></div>)}</div>
    <Card className="admin-panel-card p-5"><h2 className="text-lg font-black">Revenue Concentration</h2><p className="mt-1 text-xs font-semibold text-slate-500">Pareto view covers {coverage.toLowerCase()}; revenue is before bill-level discounts.</p><div className="mt-4 h-[360px] min-h-[360px]">{pareto.length ? <ResponsiveContainer width="100%" height="100%"><ComposedChart data={pareto} margin={{top:8,right:8,left:0,bottom:82}}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" interval={0} angle={-32} textAnchor="end" height={90} tick={{fontSize:10}} tickFormatter={compactProductName} /><YAxis yAxisId="money" tickFormatter={(v) => `${Math.round(v/1000)}K`} /><YAxis yAxisId="pct" orientation="right" domain={[0,100]} tickFormatter={(v) => `${v}%`} /><Tooltip labelFormatter={(name) => String(name)} formatter={(v,n) => n === "cumulative" ? `${Number(v).toFixed(1)}%` : formatCurrency(v)} /><Bar yAxisId="money" dataKey="revenue" fill="#2563eb" radius={[6,6,0,0]} /><Line yAxisId="pct" dataKey="cumulative" stroke="#dc2626" strokeWidth={2} /></ComposedChart></ResponsiveContainer> : null}</div></Card>
    <Card className="admin-panel-card overflow-hidden p-0" title="Product Performance"><div className="flex flex-wrap gap-2 border-b border-slate-200 p-4">{filters.map(f => <button key={f.id} onClick={() => setFilter(f.id)} className={`rounded-full px-3 py-2 text-xs font-bold ${filter === f.id ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-600"}`}>{f.label}</button>)}</div><div className="space-y-3 p-4 md:hidden">{filtered.map(r => <div key={r.itemId} className="rounded-xl border border-slate-200 p-4"><p className="font-black">{r.itemName}</p><p className="mt-1 text-xs text-slate-500">{r.itemType} · {qty(r.qtySold,r.qtyUnit)}</p><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-slate-500">Revenue</p><p className="font-bold">{formatCurrency(r.revenue)}</p></div><div><p className="text-xs text-slate-500">Profit / Margin</p><p className={Number(r.profit)<0?"font-bold text-red-700":"font-bold text-emerald-700"}>{formatCurrency(r.profit)} · {Number(r.marginPercent||0).toFixed(1)}%</p></div></div></div>)}</div><div className="hidden md:block"><Table columns={[{header:"Item",render:r=><div><p className="font-bold">{r.itemName}</p><p className="text-xs text-slate-500">{r.itemType}</p></div>},{header:"Qty Sold",render:r=>qty(r.qtySold,r.qtyUnit)},{header:"Revenue",render:r=>formatCurrency(r.revenue)},{header:"Cost",render:r=>formatCurrency(r.cost)},{header:"Profit",render:r=><span className={Number(r.profit)<0?"font-bold text-red-700":"font-bold text-emerald-700"}>{formatCurrency(r.profit)}</span>},{header:"Margin",render:r=>`${Number(r.marginPercent||0).toFixed(1)}%`}]} data={filtered} /></div></Card>
  </div>;
}
