/**
 * The promotion pricing engine, ported for the till.
 *
 * This is a line-for-line port of the server's `PromotionEvaluator` (backend,
 * `com.chala.posapp.promotion.engine`). The server is canonical; this file exists so an
 * offline till prices a cart the way the server would have, instead of charging list price
 * and switching every promotion off the moment the connection drops.
 *
 * The two are kept honest by a shared fixture corpus: `promotion-corpus.json` is generated by
 * the server's test suite from its engine, and `__tests__/promotionEngine.corpus.test.mjs`
 * runs this engine over the same inputs and fails on any difference. Do not "fix" a
 * discrepancy here without changing the server first, the corpus is the contract.
 *
 * Money is BigInt at six decimal places, rounded half-up, because the server computes in
 * BigDecimal and floating point would drift on the second cart. Inputs arrive as the JSON
 * the `/promotions/bundle` endpoint sends: snapshots with numbers and ISO strings.
 */

// ── money ────────────────────────────────────────────────────────────────────────────────

const SCALE = 1_000_000n;          // six decimal places
const CENT = 10_000n;              // one cent, in scaled units
const HUNDRED = 100n * SCALE;

/** Parse a number, numeric string or null into scaled BigInt. Truncates beyond six places. */
export const money = (value) => {
  if (value == null || value === "") return 0n;
  if (typeof value === "bigint") return value;
  const text = typeof value === "number" ? value.toFixed(6) : String(value).trim();
  const negative = text.startsWith("-");
  const [whole, fraction = ""] = text.replace("-", "").split(".");
  const scaled = BigInt(whole || "0") * SCALE + BigInt((fraction + "000000").slice(0, 6));
  return negative ? -scaled : scaled;
};

/** Integer division rounded half away from zero, BigDecimal's HALF_UP. */
const divRound = (numerator, denominator) => {
  if (denominator === 0n) return 0n;
  const negative = (numerator < 0n) !== (denominator < 0n);
  const n = numerator < 0n ? -numerator : numerator;
  const d = denominator < 0n ? -denominator : denominator;
  const q = (n + d / 2n) / d;
  return negative ? -q : q;
};

const mul = (a, b) => divRound(a * b, SCALE);
const max = (a, b) => (a > b ? a : b);
const min = (a, b) => (a < b ? a : b);
const nonNegative = (a) => (a < 0n ? 0n : a);
/** Round to two places, half-up, staying in scaled units. */
const round2 = (a) => divRound(a, CENT) * CENT;
/** (numerator / denominator) rounded to two places in one step, as BigDecimal.divide(…, 2, HALF_UP). */
const roundDiv2 = (numerator, denominator) => divRound(numerator, denominator * CENT) * CENT;
/** Scaled BigInt to a JS number with two decimals, what the server's doubles carry. */
export const toNumber = (a) => Number(a) / 1_000_000;
const out = (a) => Number((Number(a) / 1_000_000).toFixed(2));

// ── quantities ───────────────────────────────────────────────────────────────────────────

const MEASURED = new Set(["NORMAL", "WEIGHT", "VOLUME"]);

/** A line total at a unit price. Quantities are normalized base units (1000 per primary unit). */
const lineTotal = (itemType, unitPrice, normalizedQty) => {
  const qty = BigInt(Math.trunc(Number(normalizedQty) || 0));
  return MEASURED.has(itemType)
    ? roundDiv2(unitPrice * qty, 1000n)
    : round2(unitPrice * qty);
};

/** Quantity in primary units, pieces, kilograms, litres, scaled. */
const primaryUnits = (itemType, normalizedQty) => {
  const qty = BigInt(Math.trunc(Number(normalizedQty) || 0));
  return MEASURED.has(itemType) ? divRound(qty * SCALE, 1000n) : qty * SCALE;
};

// ── rates ────────────────────────────────────────────────────────────────────────────────

const finalUnitPrice = (unitPrice, type, value) => {
  const price = nonNegative(unitPrice);
  if (!type || type === "NONE" || value == null) return price;
  if (type === "PERCENT") {
    const percent = min(max(money(value), 0n), HUNDRED);
    return price - divRound(price * percent, HUNDRED);
  }
  const amount = min(max(money(value), 0n), price);
  return price - amount;
};

/** The unit price that produces a given line discount; linear, so it holds for weight items. */
const unitPriceForLineDiscount = (unitPrice, baseLineTotal, lineDiscount) => {
  if (baseLineTotal <= 0n) return unitPrice;
  return divRound(unitPrice * nonNegative(baseLineTotal - lineDiscount), baseLineTotal);
};

const marginPercent = (price, cost) => (price <= 0n ? null : divRound((price - cost) * HUNDRED, price));

// ── snapshot helpers ─────────────────────────────────────────────────────────────────────

const CART_LEVEL = new Set(["BUNDLE", "CHEAPEST_FREE"]);

const effectOf = (p) => p.effectType || "DISCOUNT";
const stackingOf = (p) => p.stackingMode || "BEST_ONLY";
const isLineLevel = (p) => (p.scope === "ITEM" || p.scope === "CATEGORY") && !CART_LEVEL.has(effectOf(p));
const isOrderLevel = (p) => p.scope === "BILL" || p.scope === "CUSTOMER" || CART_LEVEL.has(effectOf(p));
const matchesTargetsByItem = (p) => p.scope === "ITEM" || p.scope === "CATEGORY";
const hasOwnRate = (t) => !!t && t.discountType != null && t.discountType !== "NONE" && t.discountValue != null;

const parseLocal = (iso) => (iso ? new Date(iso) : null);
const hhmmss = (date) =>
  `${String(date.getHours()).padStart(2, "0")}:${String(date.getMinutes()).padStart(2, "0")}:${String(date.getSeconds()).padStart(2, "0")}`;
const normTime = (t) => (t == null ? null : String(t).length === 5 ? `${t}:00` : String(t).slice(0, 8));

const scheduleMatches = (schedule, date) => {
  const days = Number(schedule.daysOfWeek || 0);
  if (days !== 0) {
    const isoDay = ((date.getDay() + 6) % 7) + 1; // Monday = 1 … Sunday = 7
    if ((days & (1 << (isoDay - 1))) === 0) return false;
  }
  const start = normTime(schedule.startTime);
  const end = normTime(schedule.endTime);
  if (!start || !end) return true;
  const now = hhmmss(date);
  if (end >= start) return now >= start && now <= end;
  return now >= start || now <= end; // overnight
};

/** Inside the date window and, if scheduled, inside at least one schedule. */
export const isRunningAt = (promotion, date) => {
  const start = parseLocal(promotion.startAt);
  const end = parseLocal(promotion.endAt);
  if (!start || !end || start > date || end < date) return false;
  const schedules = promotion.schedules || [];
  if (schedules.length === 0) return true;
  return schedules.some((s) => scheduleMatches(s, date));
};

export const coversBranch = (promotion, branchId) =>
  promotion.branchId == null || Number(promotion.branchId) === Number(branchId);

// ── matching ─────────────────────────────────────────────────────────────────────────────

const same = (a, b) => a != null && b != null && Number(a) === Number(b);

const matchingTarget = (promotion, line) => {
  const targets = promotion.targets || [];
  if (promotion.scope === "ITEM") {
    return targets.find((t) => same(t.itemId, line.itemId)) || null;
  }
  return targets.find((t) =>
    (t.subCategoryId != null && same(t.subCategoryId, line.subCategoryId))
    || (t.categoryId != null && same(t.categoryId, line.categoryId))) || null;
};

const matchesCustomer = (promotion, customerId) => {
  if (promotion.scope !== "CUSTOMER") return true;
  if (customerId == null || Number(customerId) <= 0) return false;
  return (promotion.targets || []).some((t) => same(t.customerId, customerId));
};

// ── guards ───────────────────────────────────────────────────────────────────────────────

const marginVerdict = (promotion, costPrice, discountedUnitPrice) => {
  if (costPrice == null) return null;
  const cost = money(costPrice);
  if (!promotion.allowBelowCost && discountedUnitPrice < cost) return "BELOW_COST";
  if (promotion.marginFloorPercent != null) {
    const margin = marginPercent(discountedUnitPrice, cost);
    if (margin == null || margin < money(promotion.marginFloorPercent)) return "BELOW_MARGIN_FLOOR";
  }
  return null;
};

const capDiscount = (promotion, discount) => {
  const cap = nonNegative(money(promotion.maxDiscountAmount));
  return cap <= 0n ? round2(discount) : round2(min(discount, cap));
};

// ── decisions ────────────────────────────────────────────────────────────────────────────

const decision = (promotion, outcome, discount = 0n) => ({
  promotionId: promotion.id,
  promotionName: promotion.name,
  outcome,
  discount: out(round2(discount)),
});

// ── selection ────────────────────────────────────────────────────────────────────────────

const select = (applicable) => {
  let winner = null;
  for (const a of applicable) {
    if (stackingOf(a.promotion) === "STACKABLE") continue;
    if (winner == null || a.discount > winner.discount) winner = a;
  }
  if (winner && stackingOf(winner.promotion) === "EXCLUSIVE") return { chosen: [winner], exclusive: true };
  return { chosen: applicable.filter((a) => a === winner || stackingOf(a.promotion) === "STACKABLE"), exclusive: false };
};

const fillDecisions = (decisions, applicable, selection) => {
  for (const a of applicable) {
    const outcome = selection.chosen.includes(a) ? "APPLIED"
      : selection.exclusive && stackingOf(a.promotion) === "STACKABLE" ? "BLOCKED_BY_EXCLUSIVE"
      : "LOST_TO_BETTER";
    decisions[a.index] = decision(a.promotion, outcome, a.discount);
  }
};

// ── line effects ─────────────────────────────────────────────────────────────────────────

const highestQtyTier = (promotion, units) => {
  let best = null;
  for (const tier of promotion.tiers || []) {
    if (tier.minQty == null) continue;
    const minQty = money(tier.minQty);
    if (units < minQty) continue;
    if (best == null || minQty > money(best.minQty)) best = tier;
  }
  return best;
};

/** Uncapped discount, `null` for a tier not reached, `0n` for nothing to give. */
const lineEffectDiscount = (promotion, target, line, unitPrice, baseLineTotal) => {
  const total = (price) => lineTotal(line.itemType, price, line.normalizedQty);
  if (target.offerPrice != null) {
    return baseLineTotal - total(min(nonNegative(money(target.offerPrice)), unitPrice));
  }
  if (hasOwnRate(target)) {
    return baseLineTotal - total(finalUnitPrice(unitPrice, target.discountType, target.discountValue));
  }
  switch (effectOf(promotion)) {
    case "DISCOUNT":
      return baseLineTotal - total(finalUnitPrice(unitPrice, promotion.discountType, promotion.discountValue));
    case "FIXED_PRICE":
      return baseLineTotal - total(min(nonNegative(money(promotion.discountValue)), unitPrice));
    case "BUY_X_GET_Y_FREE": {
      const buy = nonNegative(money(promotion.buyQty));
      const get = nonNegative(money(promotion.getQty));
      if (buy <= 0n || get <= 0n) return 0n;
      const units = primaryUnits(line.itemType, line.normalizedQty);
      const groups = units / (buy + get); // BigInt division floors
      return round2(mul(groups * get, unitPrice));
    }
    case "PROFIT_SHARE": {
      // Share of margin, not of price. Mirrors PromotionEvaluator: unknown or non-positive
      // cost gives nothing away, and the share is capped at the whole margin so the line
      // can never fall below its own cost.
      const cost = money(line.costPrice);
      if (cost <= 0n) return 0n;
      const profit = nonNegative(unitPrice - cost);
      if (profit <= 0n) return 0n;
      const share = min(nonNegative(money(promotion.discountValue)), HUNDRED);
      return baseLineTotal - total(unitPrice - divRound(profit * share, HUNDRED));
    }
    case "TIERED": {
      const tier = highestQtyTier(promotion, primaryUnits(line.itemType, line.normalizedQty));
      if (!tier) return null;
      return baseLineTotal - total(finalUnitPrice(unitPrice, tier.discountType, tier.discountValue));
    }
    default:
      return 0n;
  }
};

const effectiveRateType = (a) => (hasOwnRate(a.target) ? a.target.discountType : a.promotion.discountType);
const effectiveRateValue = (a) => money(hasOwnRate(a.target) ? a.target.discountValue : a.promotion.discountValue);

// ── line ─────────────────────────────────────────────────────────────────────────────────

/**
 * Prices one line. Mirrors `PromotionEvaluator.evaluateLine`.
 *
 * @param line {itemId, itemType, subCategoryId, categoryId, unitPrice, costPrice, normalizedQty,
 *             manualDiscountType, manualDiscountValue}
 * @returns {{application: object, decisions: object[]}} with the server's field names
 */
export const evaluateLine = (line, branchId, cartBaseSubtotal, promotions) => {
  const unitPrice = nonNegative(money(line.unitPrice));
  const baseLineTotal = lineTotal(line.itemType, unitPrice, line.normalizedQty);
  const safeSubtotal = nonNegative(money(cartBaseSubtotal));
  const manualType = line.manualDiscountType || "NONE";
  const manualValue = money(line.manualDiscountValue);

  const decisions = [];
  const applicable = [];

  for (const promotion of promotions || []) {
    if (!isLineLevel(promotion)) { decisions.push(decision(promotion, "WRONG_SCOPE")); continue; }
    // The cashier took the offers off this line. Recorded as a deliberate exclusion rather
    // than as something the engine never saw, so the trace still answers "why no discount?".
    if (line.excludePromotions) { decisions.push(decision(promotion, "EXCLUDED_BY_CASHIER")); continue; }
    if (!coversBranch(promotion, branchId)) { decisions.push(decision(promotion, "BRANCH_MISMATCH")); continue; }
    if (safeSubtotal < nonNegative(money(promotion.minBillAmount))) { decisions.push(decision(promotion, "BELOW_MIN_BILL")); continue; }
    const target = matchingTarget(promotion, line);
    if (!target) { decisions.push(decision(promotion, "NO_TARGET_MATCH")); continue; }
    const uncapped = lineEffectDiscount(promotion, target, line, unitPrice, baseLineTotal);
    if (uncapped === null) { decisions.push(decision(promotion, "NO_TIER_REACHED")); continue; }
    if (uncapped <= 0n) { decisions.push(decision(promotion, "NO_DISCOUNT")); continue; }
    const effectiveUnit = unitPriceForLineDiscount(unitPrice, baseLineTotal, uncapped);
    const verdict = marginVerdict(promotion, line.costPrice, effectiveUnit);
    if (verdict) { decisions.push(decision(promotion, verdict)); continue; }
    const capped = capDiscount(promotion, uncapped);
    applicable.push({ promotion, target, discount: capped, uncapped, index: decisions.length });
    decisions.push(null);
  }

  const selection = select(applicable);
  fillDecisions(decisions, applicable, selection);

  if (selection.chosen.length === 0) {
    const manualUnit = finalUnitPrice(unitPrice, manualType, manualValue);
    const manualLineTotal = lineTotal(line.itemType, manualUnit, line.normalizedQty);
    const manualDiscount = round2(baseLineTotal - manualLineTotal);
    return {
      application: {
        promotionId: null,
        promotionName: null,
        discountType: manualType,
        discountValue: manualType === "NONE" ? 0 : out(nonNegative(manualValue)),
        manualDiscountAmount: out(manualDiscount),
        promotionDiscountAmount: 0,
        appliedDiscountAmount: out(manualDiscount),
        baseLineTotal: out(baseLineTotal),
        finalLineTotal: out(manualLineTotal),
        promotionApplied: false,
        appliedPromotionIds: [],
        exclusive: false,
      },
      decisions,
    };
  }

  const promoDiscount = min(selection.chosen.reduce((sum, a) => sum + a.discount, 0n), baseLineTotal);
  const promoUnit = unitPriceForLineDiscount(unitPrice, baseLineTotal, promoDiscount);

  const manualBlocker = manualType === "NONE" ? null
    : selection.chosen.find((a) => a.promotion.allowManualStacking === false) || null;
  const effectiveManualType = manualBlocker ? "NONE" : manualType;
  if (manualBlocker) decisions.push(decision(manualBlocker.promotion, "MANUAL_BLOCKED"));

  const stackedUnit = finalUnitPrice(promoUnit, effectiveManualType, manualValue);
  const promoLineTotal = lineTotal(line.itemType, promoUnit, line.normalizedQty);
  const finalLineTotal = lineTotal(line.itemType, stackedUnit, line.normalizedQty);
  const manualDiscount = round2(promoLineTotal - finalLineTotal);
  const appliedDiscount = round2(baseLineTotal - finalLineTotal);

  const primary = selection.chosen.reduce((best, a) => (best == null || a.discount > best.discount ? a : best), null);
  const single = selection.chosen.length === 1;
  const capApplied = primary.discount < primary.uncapped;
  const plainRate = hasOwnRate(primary.target)
    || (primary.target.offerPrice == null && effectOf(primary.promotion) === "DISCOUNT");
  const rateIntact = single && effectiveManualType === "NONE" && !capApplied && plainRate;
  const effectiveType = rateIntact ? effectiveRateType(primary) : "FIXED";
  const effectiveValue = rateIntact ? effectiveRateValue(primary) : round2(nonNegative(unitPrice - stackedUnit));

  return {
    application: {
      promotionId: primary.promotion.id,
      promotionName: single ? primary.promotion.name : selection.chosen.map((a) => a.promotion.name).join(" + "),
      discountType: effectiveType,
      discountValue: out(effectiveValue),
      manualDiscountAmount: out(manualDiscount),
      promotionDiscountAmount: out(promoDiscount),
      appliedDiscountAmount: out(appliedDiscount),
      baseLineTotal: out(baseLineTotal),
      finalLineTotal: out(finalLineTotal),
      promotionApplied: true,
      appliedPromotionIds: selection.chosen.map((a) => a.promotion.id),
      exclusive: selection.exclusive,
    },
    decisions,
  };
};

// ── bill effects ─────────────────────────────────────────────────────────────────────────

const rateOf = (amount, type, value) => {
  if (type === "PERCENT") {
    const percent = min(max(money(value), 0n), HUNDRED);
    return round2(divRound(amount * percent, HUNDRED));
  }
  if (type === "FIXED") return round2(nonNegative(money(value)));
  return 0n;
};

const highestAmountTier = (promotion, amount) => {
  let best = null;
  for (const tier of promotion.tiers || []) {
    if (tier.minAmount == null) continue;
    const minAmount = money(tier.minAmount);
    if (amount < minAmount) continue;
    if (best == null || minAmount > money(best.minAmount)) best = tier;
  }
  return best;
};

const groupSize = (promotion) => Number(nonNegative(money(promotion.buyQty)) / SCALE);

/** Every eligible whole unit as its own price, dearest first; capped like the server. */
const eligibleUnitPrices = (promotion, lines) => {
  const HARD_CAP = 10_000;
  const units = [];
  for (const line of lines) {
    const eligible = !matchesTargetsByItem(promotion) || matchingTarget(promotion, line) != null;
    if (!eligible) continue;
    const whole = Number(primaryUnits(line.itemType, line.normalizedQty) / SCALE);
    const price = nonNegative(money(line.unitPrice));
    for (let i = 0; i < whole && units.length < HARD_CAP; i++) units.push(price);
  }
  units.sort((a, b) => (a > b ? -1 : a < b ? 1 : 0));
  return units;
};

const bundleDiscount = (promotion, lines) => {
  const size = groupSize(promotion);
  if (size < 2) return 0n;
  const units = eligibleUnitPrices(promotion, lines);
  const bundlePrice = nonNegative(money(promotion.discountValue));
  let discount = 0n;
  for (let start = 0; start + size <= units.length; start += size) {
    let groupSum = 0n;
    for (let i = start; i < start + size; i++) groupSum += units[i];
    const saving = groupSum - bundlePrice;
    if (saving > 0n) discount += saving;
  }
  return round2(discount);
};

const cheapestFreeDiscount = (promotion, lines) => {
  const size = groupSize(promotion);
  if (size < 2) return 0n;
  const units = eligibleUnitPrices(promotion, lines);
  let discount = 0n;
  for (let start = 0; start + size <= units.length; start += size) discount += units[start + size - 1];
  return round2(discount);
};

const orderEffectDiscount = (promotion, baseTotal, lines) => {
  switch (effectOf(promotion)) {
    case "DISCOUNT": return rateOf(baseTotal, promotion.discountType, promotion.discountValue);
    case "TIERED": {
      const tier = highestAmountTier(promotion, baseTotal);
      if (!tier) return null;
      return rateOf(baseTotal, tier.discountType, tier.discountValue);
    }
    case "BUNDLE": return bundleDiscount(promotion, lines);
    case "CHEAPEST_FREE": return cheapestFreeDiscount(promotion, lines);
    default: return 0n;
  }
};

// ── bill ─────────────────────────────────────────────────────────────────────────────────

/** Prices the bill. Mirrors `PromotionEvaluator.evaluateOrder`. */
export const evaluateOrder = (branchId, customerId, baseTotal, manualBillDiscount, pricedLines, linesHaveExclusive, promotions) => {
  const safeBase = nonNegative(money(baseTotal));
  const manualDiscount = round2(min(nonNegative(money(manualBillDiscount)), safeBase));
  const lines = pricedLines || [];

  const decisions = [];
  const applicable = [];

  for (const promotion of promotions || []) {
    if (!isOrderLevel(promotion)) { decisions.push(decision(promotion, "WRONG_SCOPE")); continue; }
    if (linesHaveExclusive) { decisions.push(decision(promotion, "BLOCKED_BY_EXCLUSIVE")); continue; }
    if (!coversBranch(promotion, branchId)) { decisions.push(decision(promotion, "BRANCH_MISMATCH")); continue; }
    if (safeBase < nonNegative(money(promotion.minBillAmount))) { decisions.push(decision(promotion, "BELOW_MIN_BILL")); continue; }
    if (!matchesCustomer(promotion, customerId)) { decisions.push(decision(promotion, "CUSTOMER_MISMATCH")); continue; }
    const uncapped = orderEffectDiscount(promotion, safeBase, lines);
    if (uncapped === null) { decisions.push(decision(promotion, "NO_TIER_REACHED")); continue; }
    if (uncapped <= 0n) { decisions.push(decision(promotion, "NO_DISCOUNT")); continue; }
    const capped = min(capDiscount(promotion, uncapped), safeBase);
    applicable.push({ promotion, target: null, discount: capped, uncapped, index: decisions.length });
    decisions.push(null);
  }

  const selection = select(applicable);
  fillDecisions(decisions, applicable, selection);

  const promoDiscount = min(selection.chosen.reduce((sum, a) => sum + a.discount, 0n), safeBase);

  if (selection.chosen.length > 0 && promoDiscount > manualDiscount) {
    const primary = selection.chosen.reduce((best, a) => (best == null || a.discount > best.discount ? a : best), null);
    const single = selection.chosen.length === 1;
    return {
      application: {
        promotionId: primary.promotion.id,
        promotionName: single ? primary.promotion.name : selection.chosen.map((a) => a.promotion.name).join(" + "),
        discountType: primary.promotion.discountType,
        discountValue: out(money(primary.promotion.discountValue)),
        manualBillDiscountAmount: out(manualDiscount),
        promotionDiscountAmount: out(promoDiscount),
        appliedDiscountAmount: out(promoDiscount),
        baseTotal: out(safeBase),
        finalTotal: out(round2(safeBase - promoDiscount)),
        promotionApplied: true,
        appliedPromotionIds: selection.chosen.map((a) => a.promotion.id),
      },
      decisions,
    };
  }

  for (const a of selection.chosen) decisions[a.index] = decision(a.promotion, "LOST_TO_MANUAL", a.discount);
  return {
    application: {
      promotionId: null,
      promotionName: null,
      discountType: "FIXED",
      discountValue: out(manualDiscount),
      manualBillDiscountAmount: out(manualDiscount),
      promotionDiscountAmount: out(promoDiscount),
      appliedDiscountAmount: out(manualDiscount),
      baseTotal: out(safeBase),
      finalTotal: out(round2(safeBase - manualDiscount)),
      promotionApplied: false,
      appliedPromotionIds: [],
    },
    decisions,
  };
};

// ── cart convenience ─────────────────────────────────────────────────────────────────────

/**
 * Price a whole cart offline: the running promotions from a bundle, the two passes, in the
 * order the server does them. Returns what the online preview returns, so the till renders
 * both the same way.
 */
export const priceCart = ({ bundle, branchId, customerId, at = new Date(), lines, billDiscount = 0 }) => {
  const running = (bundle?.promotions || []).filter((p) => isRunningAt(p, at) && coversBranch(p, branchId));
  const cartBase = lines.reduce(
    (sum, line) => sum + lineTotal(line.itemType, nonNegative(money(line.unitPrice)), line.normalizedQty), 0n);

  const items = [];
  const priced = [];
  let exclusive = false;
  for (const line of lines) {
    const result = evaluateLine(line, branchId, cartBase, running);
    items.push({ itemId: line.itemId, ...result.application, decisions: result.decisions });
    exclusive = exclusive || result.application.exclusive;
    priced.push({
      ...line,
      manualDiscountType: "NONE",
      manualDiscountValue: 0,
      unitPrice: toNumber(unitPriceForLineDiscount(
        nonNegative(money(line.unitPrice)), money(result.application.baseLineTotal), money(result.application.appliedDiscountAmount))),
    });
  }
  const subtotalAfterLines = items.reduce((sum, item) => sum + item.finalLineTotal, 0);
  const lineDiscountTotal = items.filter((i) => i.promotionApplied).reduce((sum, i) => sum + i.promotionDiscountAmount, 0);
  const bill = evaluateOrder(branchId, customerId, subtotalAfterLines, billDiscount, priced, exclusive, running);
  const order = bill.application;

  return {
    bundleVersion: bundle?.version || null,
    items,
    promotionDiscountTotal: Number((lineDiscountTotal + (order.promotionApplied ? order.promotionDiscountAmount : 0)).toFixed(2)),
    billPromotionId: order.promotionApplied ? order.promotionId : null,
    billPromotionName: order.promotionApplied ? order.promotionName : null,
    manualBillDiscountAmount: order.manualBillDiscountAmount,
    billPromotionDiscountAmount: order.promotionApplied ? order.promotionDiscountAmount : 0,
    appliedBillDiscountAmount: order.appliedDiscountAmount,
    finalTotal: order.finalTotal,
    billPromotionApplied: order.promotionApplied,
    billDecisions: bill.decisions,
  };
};
