import { useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, ClipboardList, PackageCheck } from 'lucide-react';
import { toast } from 'react-hot-toast';
import Card from '../components/common/Card'; import Button from '../components/common/Button';
import { reorderPlansAPI } from '../api/reorderPlans.api'; import { branchesAPI } from '../api/branches.api'; import { suppliersAPI } from '../api/suppliers.api'; import { formatCurrency } from '../utils/formatters';
const badge={DRAFT:'bg-slate-100 text-slate-700',PENDING_APPROVAL:'bg-amber-100 text-amber-700',APPROVED:'bg-emerald-100 text-emerald-700',REJECTED:'bg-rose-100 text-rose-700',CONVERTED:'bg-blue-100 text-blue-700',CANCELED:'bg-slate-100 text-slate-500'};
export default function ProcurementPlanningPage(){
 const [plans,setPlans]=useState([]),[selected,setSelected]=useState(null),[drafts,setDrafts]=useState([]),[branches,setBranches]=useState([]),[suppliers,setSuppliers]=useState([]),[form,setForm]=useState({name:'Weekly reorder plan',branchId:'',forecastDays:30,targetCoverDays:30});
 const load=async()=>{const r=await reorderPlansAPI.list();setPlans(r.data||[]);if(selected){const fresh=(r.data||[]).find(x=>x.id===selected.id);if(fresh)setSelected(fresh);}};
 useEffect(()=>{Promise.all([load(),branchesAPI.getAll(true),suppliersAPI.list({page:0,size:100})]).then(([,b,s])=>{setBranches(b.data||[]);setSuppliers(s.data?.items||s.data?.content||s.data||[]);}).catch(()=>toast.error('Could not load procurement planning'));},[]);
 const create=async()=>{try{const r=await reorderPlansAPI.create({...form,branchId:form.branchId?Number(form.branchId):null});setSelected(r.data);await load();toast.success('Reorder plan created');}catch{toast.error('Could not create reorder plan');}};
 const action=async(name,arg)=>{try{const r=await reorderPlansAPI[name](selected.id,arg);setSelected(r.data);setDrafts([]);await load();toast.success('Plan updated');}catch{toast.error('Could not update plan');}};
 const edit=async(line,patch)=>{try{const r=await reorderPlansAPI.updateLine(selected.id,line.id,{approvedQty:Number(patch.approvedQty??line.approvedQty),supplierId:patch.supplierId===undefined?line.supplierId:(patch.supplierId?Number(patch.supplierId):null),excluded:patch.excluded??line.excluded,editNote:patch.editNote??line.editNote});setSelected(r.data);await load();}catch{toast.error('Could not edit line');}};
 const preview=async()=>{try{const r=await reorderPlansAPI.purchaseDrafts(selected.id);setDrafts(r.data||[]);}catch(e){toast.error(e.response?.data?.detail||'Assign suppliers before conversion');}};
 return <div className="space-y-6 p-4 md:p-6"><div><h1 className="text-2xl font-black text-slate-900">Procurement Planning</h1><p className="text-sm text-slate-500">Review forecast suggestions before using the existing purchase workflow. Plans never change stock.</p></div>
 <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><p className="font-black">Planning layer only</p><p className="mt-1">Creating, approving, or converting a plan does not create a purchase, GRN, supplier payment, or stock movement.</p></div>
 <Card className="p-4" title="Generate Plan"><div className="grid gap-3 md:grid-cols-5"><input className="h-10 w-full rounded-lg border px-3 text-sm" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select className="h-10 w-full rounded-lg border px-3 text-sm" value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})}><option value="">All branches</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select className="h-10 w-full rounded-lg border px-3 text-sm" value={form.forecastDays} onChange={e=>setForm({...form,forecastDays:Number(e.target.value)})}><option value={14}>14-day forecast</option><option value={30}>30-day forecast</option><option value={60}>60-day forecast</option></select><select className="h-10 w-full rounded-lg border px-3 text-sm" value={form.targetCoverDays} onChange={e=>setForm({...form,targetCoverDays:Number(e.target.value)})}><option value={14}>14-day cover</option><option value={30}>30-day cover</option><option value={60}>60-day cover</option></select><Button onClick={create}>Generate Draft</Button></div></Card>
 <div className="grid gap-6 xl:grid-cols-[320px,1fr]"><Card className="p-3" title="Saved Plans"><div className="space-y-2">{plans.length===0?<p className="p-4 text-sm text-slate-500">No saved plans yet.</p>:plans.map(p=><button key={p.id} onClick={()=>{setSelected(p);setDrafts([])}} className={`w-full rounded-xl border p-3 text-left ${selected?.id===p.id?'border-blue-500 bg-blue-50':'border-slate-200 bg-white'}`}><div className="flex justify-between gap-2"><p className="font-bold text-slate-900">{p.name}</p><span className={`rounded-full px-2 py-1 text-[10px] font-black ${badge[p.status]}`}>{p.status}</span></div><p className="mt-1 text-xs text-slate-500">{p.lines.length} lines · {new Date(p.createdAt).toLocaleString()}</p></button>)}</div></Card>
 <div>{!selected?<Card className="p-10 text-center"><ClipboardList className="mx-auto text-slate-300"/><p className="mt-3 font-bold text-slate-700">Select or generate a plan</p></Card>:<div className="space-y-4"><Card className="p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-black">{selected.name}</h2><p className="text-xs text-slate-500">Created by {selected.createdByUsername}</p></div><div className="flex flex-wrap gap-2">{selected.status==='DRAFT'&&<Button onClick={()=>action('submit')}>Submit for approval</Button>}{selected.status==='PENDING_APPROVAL'&&<><Button onClick={()=>action('approve')}>Approve</Button><Button variant="outline" onClick={()=>{const r=prompt('Rejection reason');if(r)action('reject',r)}}>Reject</Button></>}{selected.status==='APPROVED'&&<Button onClick={preview}>Preview purchase handoff</Button>}</div></div></Card>
 <Card className="overflow-hidden p-0" title="Plan Lines"><div className="space-y-3 p-4 md:hidden">{selected.lines.map(l=><LineCard key={l.id} line={l} editable={selected.status==='DRAFT'} suppliers={suppliers} edit={edit}/>)}</div><div className="hidden overflow-x-auto md:block"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-3">Item</th><th className="p-3">Demand Source</th><th className="p-3">Qty</th><th className="p-3">Supplier</th><th className="p-3">Estimated</th><th className="p-3">Exclude</th></tr></thead><tbody>{selected.lines.map(l=><tr key={l.id} className="border-t"><td className="p-3"><p className="font-bold">{l.itemName}</p><p className="text-xs text-slate-500">{l.confidence} confidence</p></td><td className="p-3 text-xs"><p>Direct: {l.directDemandBase}</p><p>Recipes: {l.recipeDemandBase}</p><p className="font-bold">Total base: {l.totalDemandBase}</p></td><td className="p-3"><input disabled={selected.status!=='DRAFT'} type="number" min="0" step="0.001" className="w-24 rounded border px-2 py-1" defaultValue={l.approvedQty} onBlur={e=>edit(l,{approvedQty:e.target.value})}/><p className="mt-1 text-[10px] text-slate-500">{l.suggestedQtyBase} base units</p></td><td className="p-3"><select disabled={selected.status!=='DRAFT'} className="rounded border px-2 py-1" value={l.supplierId||''} onChange={e=>edit(l,{supplierId:e.target.value})}><option value="">Unassigned</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></td><td className="p-3">{formatCurrency(Number(l.approvedQty)*Number(l.unitCost))}</td><td className="p-3"><input disabled={selected.status!=='DRAFT'} type="checkbox" checked={l.excluded} onChange={e=>edit(l,{excluded:e.target.checked})}/></td></tr>)}</tbody></table></div></Card>
 {drafts.length>0&&<Card className="p-4" title="Purchase Handoff Preview"><div className="space-y-3">{drafts.map(d=><div key={d.supplierId} className="rounded-xl border p-4"><div className="flex justify-between"><div><p className="font-black">{d.supplierName}</p><p className="text-xs text-slate-500">{d.items.length} items</p></div><p className="font-black">{formatCurrency(d.estimatedTotal)}</p></div></div>)}</div><div className="mt-4 flex items-start gap-2 rounded-lg bg-blue-50 p-3 text-xs text-blue-800"><PackageCheck size={16}/><p>Use these groups to create purchases in the existing purchase form. Record the purchase or handoff reference afterward.</p></div><Button className="mt-3" onClick={()=>{const ref=prompt('Purchase or handoff reference');if(ref)action('markConverted',ref)}}>Mark handoff complete</Button></Card>}</div>}</div></div></div>;
}
function LineCard({line,editable,suppliers,edit}){return <div className="rounded-xl border p-4"><div className="flex justify-between"><div><p className="font-black">{line.itemName}</p><p className="text-xs text-slate-500">{line.confidence} confidence</p></div>{line.supplierId? <CheckCircle2 className="text-emerald-500" size={18}/>:<AlertTriangle className="text-amber-500" size={18}/>}</div><div className="mt-3 rounded-lg bg-slate-50 p-2 text-xs text-slate-600"><p>Direct demand: {line.directDemandBase} base</p><p>Recipe demand: {line.recipeDemandBase} base</p><p className="font-bold">Total demand: {line.totalDemandBase} base</p></div><div className="mt-3 grid grid-cols-2 gap-2"><input disabled={!editable} type="number" min="0" step="0.001" className="rounded border px-2 py-2" defaultValue={line.approvedQty} onBlur={e=>edit(line,{approvedQty:e.target.value})}/><select disabled={!editable} className="rounded border px-2 py-2" value={line.supplierId||''} onChange={e=>edit(line,{supplierId:e.target.value})}><option value="">Unassigned</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><p className="mt-1 text-[10px] text-slate-500">Approved: {line.suggestedQtyBase} integer base units</p><label className="mt-3 flex gap-2 text-sm"><input disabled={!editable} type="checkbox" checked={line.excluded} onChange={e=>edit(line,{excluded:e.target.checked})}/>Exclude from plan</label></div>}
