export const ORDER_TYPES = {
  CASH: 'CASH',
  CREDIT: 'CREDIT',
};

export const DISCOUNT_TYPES = {
  NONE: 'NONE',
  FIXED: 'FIXED',
  PERCENT: 'PERCENT',
};

export const ItemType = {
    NORMAL: "NORMAL",
    WEIGHT: "WEIGHT",
    SERVICE: "SERVICE"
};

export const ItemTypeLabels = {
    NORMAL: "Normal Item (Stock Managed)",
    WEIGHT: "Weight Based (KG/G)",
    SERVICE: "Service / Non-Stock"
};

export const MeasurementUnit = {
  PCS: 'PCS',
  G: 'G',
  KG: 'KG',
  SERVICE: 'SERVICE',
};

export const EXPENSE_CATEGORIES = {
    TEA_AND_SNACKS: "TEA_AND_SNACKS",
    LUNCH: "LUNCH",
    STAFF_MEALS: "STAFF_MEALS",

    TRANSPORT: "TRANSPORT",
    FUEL: "FUEL",
    DELIVERY_CHARGES: "DELIVERY_CHARGES",

    ELECTRICITY_BILL: "ELECTRICITY_BILL",
    WATER_BILL: "WATER_BILL",
    INTERNET_BILL: "INTERNET_BILL",
    TELEPHONE_BILL: "TELEPHONE_BILL",
    RENT: "RENT",

    STATIONERY: "STATIONERY",
    PACKAGING_MATERIALS: "PACKAGING_MATERIALS",
    CLEANING_SUPPLIES: "CLEANING_SUPPLIES",
    SHOP_MAINTENANCE: "SHOP_MAINTENANCE",
    EQUIPMENT_REPAIRS: "EQUIPMENT_REPAIRS",

    SALARY_ADVANCE: "SALARY_ADVANCE",
    STAFF_WELFARE: "STAFF_WELFARE",

    MARKETING_AND_ADS: "MARKETING_AND_ADS",
    DONATIONS: "DONATIONS",
    MISCELLANEOUS: "MISCELLANEOUS",
    OTHER: "OTHER"
};

export const ADJUSTMENT_TYPES = {
  EXPIRED: 'EXPIRED',
  DAMAGED: 'DAMAGED',
  LOST: 'LOST',
  FOUND: 'FOUND',
  MANUAL: 'MANUAL',
};

export const TRANSFER_STATUS = {
  REQUESTED: 'REQUESTED',
  RECEIVED: 'RECEIVED',
  CANCELLED: 'CANCELLED',
};

export const KEYBOARD_SHORTCUTS = {
  SEARCH_ITEM: 'F2',
  SELECT_CUSTOMER: 'F4',
  CHECKOUT: 'F9',
  ESCAPE: 'Escape',
};
