export const PLAN_FEATURES = {
  MONTHLY_LITE: {
    DASHBOARD_ONLY: true,
    STOCK_LEVELS: false,
    ADVANCED_REPORTS: false,
    BULK_ITEMS: false,
    BARCODE_PRINT: false,
    STOCK_TRANSFERS: false,
    PURCHASES: false,
    FINANCIALS: false,
    USER_MANAGEMENT: false,
    ORDER_CANCEL: false,
    SHIFT_HISTORY: false,
  },
  MONTHLY_BASIC: {
    DASHBOARD_ONLY: true,
    STOCK_LEVELS: false,
    ADVANCED_REPORTS: false,
    BULK_ITEMS: false,
    BARCODE_PRINT: false,
    STOCK_TRANSFERS: false,
    PURCHASES: false,
    FINANCIALS: false,
    USER_MANAGEMENT: false,
    ORDER_CANCEL: false,
    SHIFT_HISTORY: false,
  },
  YEARLY_LITE: {
    DASHBOARD_ONLY: true,
    STOCK_LEVELS: false,
    ADVANCED_REPORTS: false,
    BULK_ITEMS: false,
    BARCODE_PRINT: false,
    STOCK_TRANSFERS: false,
    PURCHASES: false,
    FINANCIALS: false,
    USER_MANAGEMENT: false,
    ORDER_CANCEL: false,
    SHIFT_HISTORY: false,
  },
  MONTHLY_PRO: {
    DASHBOARD_ONLY: false,
    STOCK_LEVELS: true,
    ADVANCED_REPORTS: true,
    BULK_ITEMS: true,
    BARCODE_PRINT: true,
    STOCK_TRANSFERS: true,
    PURCHASES: true,
    FINANCIALS: true,
    USER_MANAGEMENT: true,
    ORDER_CANCEL: true,
    SHIFT_HISTORY: true,
  },
  YEARLY_PRO: {
    DASHBOARD_ONLY: false,
    STOCK_LEVELS: true,
    ADVANCED_REPORTS: true,
    BULK_ITEMS: true,
    BARCODE_PRINT: true,
    STOCK_TRANSFERS: true,
    PURCHASES: true,
    FINANCIALS: true,
    USER_MANAGEMENT: true,
    ORDER_CANCEL: true,
    SHIFT_HISTORY: true,
  },
  MONTHLY_DEMO: {
    DASHBOARD_ONLY: false,
    STOCK_LEVELS: true,
    ADVANCED_REPORTS: true,
    BULK_ITEMS: true,
    BARCODE_PRINT: true,
    STOCK_TRANSFERS: true,
    PURCHASES: true,
    FINANCIALS: true,
    USER_MANAGEMENT: true,
    ORDER_CANCEL: true,
    SHIFT_HISTORY: true,
  },
};

export const hasPlanFeature = (planName, feature) => {
  if (!feature) return true;
  if (!planName) return true;
  return PLAN_FEATURES[planName]?.[feature] ?? true;
};
