export const PLAN_FEATURES = {
  FREE: {
    DASHBOARD_ONLY: true,
    STOCK_LEVELS: false,
    ADVANCED_REPORTS: false,
    BULK_ITEMS: false,
    BARCODE_PRINT: false,
    STOCK_TRANSFERS: false,
    PURCHASES: false,
    FINANCIALS: false,
    USER_MANAGEMENT: false,
    DINING_TABLES: false,
    ORDER_CANCEL: false,
    SHIFT_HISTORY: false,
    RECIPE_ITEMS: false,
    WEIGHT_ITEMS: false,
    SERVICES: false,
  },
  STANDARD: {
    DASHBOARD_ONLY: true,
    STOCK_LEVELS: true,
    ADVANCED_REPORTS: false,
    BULK_ITEMS: true,
    BARCODE_PRINT: true,
    STOCK_TRANSFERS: false,
    PURCHASES: false,
    FINANCIALS: true,
    USER_MANAGEMENT: true,
    DINING_TABLES: true,
    ORDER_CANCEL: false,
    SHIFT_HISTORY: false,
    RECIPE_ITEMS: false,
    WEIGHT_ITEMS: true,
    SERVICES: true,
  },
  PRO: {
    DASHBOARD_ONLY: false,
    STOCK_LEVELS: true,
    ADVANCED_REPORTS: true,
    BULK_ITEMS: true,
    BARCODE_PRINT: true,
    STOCK_TRANSFERS: true,
    PURCHASES: true,
    FINANCIALS: true,
    USER_MANAGEMENT: true,
    DINING_TABLES: true,
    ORDER_CANCEL: true,
    SHIFT_HISTORY: true,
    RECIPE_ITEMS: true,
    WEIGHT_ITEMS: true,
    SERVICES: true,
  },
  MONTHLY_LITE: {
    DASHBOARD_ONLY: true,
    STOCK_LEVELS: true,
    ADVANCED_REPORTS: false,
    BULK_ITEMS: true,
    BARCODE_PRINT: true,
    STOCK_TRANSFERS: false,
    PURCHASES: false,
    FINANCIALS: true,
    USER_MANAGEMENT: true,
    DINING_TABLES: true,
    ORDER_CANCEL: false,
    SHIFT_HISTORY: false,
    RECIPE_ITEMS: false,
    WEIGHT_ITEMS: true,
    SERVICES: true,
  },
  MONTHLY_BASIC: {
    DASHBOARD_ONLY: true,
    STOCK_LEVELS: true,
    ADVANCED_REPORTS: false,
    BULK_ITEMS: true,
    BARCODE_PRINT: true,
    STOCK_TRANSFERS: false,
    PURCHASES: false,
    FINANCIALS: true,
    USER_MANAGEMENT: true,
    DINING_TABLES: true,
    ORDER_CANCEL: false,
    SHIFT_HISTORY: false,
    RECIPE_ITEMS: false,
    WEIGHT_ITEMS: true,
    SERVICES: true,
  },
  YEARLY_LITE: {
    DASHBOARD_ONLY: true,
    STOCK_LEVELS: true,
    ADVANCED_REPORTS: false,
    BULK_ITEMS: true,
    BARCODE_PRINT: true,
    STOCK_TRANSFERS: false,
    PURCHASES: false,
    FINANCIALS: true,
    USER_MANAGEMENT: true,
    DINING_TABLES: true,
    ORDER_CANCEL: false,
    SHIFT_HISTORY: false,
    RECIPE_ITEMS: false,
    WEIGHT_ITEMS: true,
    SERVICES: true,
  },
  MONTHLY_PRO: {
    DASHBOARD_ONLY: false,
    STOCK_LEVELS: true,
    ADVANCED_REPORTS: true,
    BULK_ITEMS: true,
    BARCODE_PRINT: true,
    STOCK_TRANSFERS: true,
    PURCHASES: true,
    FINANCIALS: true,
    USER_MANAGEMENT: true,
    DINING_TABLES: true,
    ORDER_CANCEL: true,
    SHIFT_HISTORY: true,
    RECIPE_ITEMS: true,
    WEIGHT_ITEMS: true,
    SERVICES: true,
  },
  YEARLY_PRO: {
    DASHBOARD_ONLY: false,
    STOCK_LEVELS: true,
    ADVANCED_REPORTS: true,
    BULK_ITEMS: true,
    BARCODE_PRINT: true,
    STOCK_TRANSFERS: true,
    PURCHASES: true,
    FINANCIALS: true,
    USER_MANAGEMENT: true,
    DINING_TABLES: true,
    ORDER_CANCEL: true,
    SHIFT_HISTORY: true,
    RECIPE_ITEMS: true,
    WEIGHT_ITEMS: true,
    SERVICES: true,
  },
  MONTHLY_DEMO: {
    DASHBOARD_ONLY: true,
    STOCK_LEVELS: false,
    ADVANCED_REPORTS: false,
    BULK_ITEMS: false,
    BARCODE_PRINT: false,
    STOCK_TRANSFERS: false,
    PURCHASES: false,
    FINANCIALS: false,
    USER_MANAGEMENT: false,
    DINING_TABLES: false,
    ORDER_CANCEL: false,
    SHIFT_HISTORY: false,
    RECIPE_ITEMS: false,
    WEIGHT_ITEMS: false,
    SERVICES: false,
  },
};

const SINGLE_BRANCH_PLANS = new Set([
  "FREE",
  "STANDARD",
  "MONTHLY_DEMO",
  "MONTHLY_LITE",
  "MONTHLY_BASIC",
  "YEARLY_LITE",
]);

export const isSingleBranchPlan = (planName) => {
  if (!planName) return false;
  return SINGLE_BRANCH_PLANS.has(planName);
};

export const hasPlanFeature = (planName, feature) => {
  if (!feature) return true;
  if (!planName) return true;
  return PLAN_FEATURES[planName]?.[feature] ?? true;
};

export const getConfigurableFeatureAvailability = (planName) => ({
  recipeItemsEnabled: hasPlanFeature(planName, 'RECIPE_ITEMS'),
  weightItemsEnabled: hasPlanFeature(planName, 'WEIGHT_ITEMS'),
  servicesEnabled: hasPlanFeature(planName, 'SERVICES'),
  tableManagementEnabled: hasPlanFeature(planName, 'DINING_TABLES'),
  dineInEnabled: hasPlanFeature(planName, 'DINING_TABLES'),
});
