import React, { forwardRef, useImperativeHandle, useRef } from 'react';

const PurchaseA4Print = forwardRef((props, ref) => {
  const printFrameRef = useRef(null);

  useImperativeHandle(ref, () => ({
    printDocument: (purchase) => {
      const frame = printFrameRef.current;
      if (!frame) return;

      const doc = frame.contentWindow.document;
      doc.open();

      // හැම Branch එකකම GRN වල Items ටික Table වලට හදනවා
      const grnHTML = purchase.grnList && purchase.grnList.map(grn => `
        <div class="grn-section">
            <h3>📍 Branch: ${grn.branchName} | GRN No: ${grn.grnNo}</h3>
            <table>
                <thead>
                    <tr>
                        <th style="width: 5%;">#</th>
                        <th style="width: 35%;">Item Name</th>
                        <th style="width: 15%;">Barcode</th>
                        <th class="text-right" style="width: 15%;">Cost (LKR)</th>
                        <th class="text-center" style="width: 10%;">Qty</th>
                        <th class="text-right" style="width: 20%;">Line Total (LKR)</th>
                    </tr>
                </thead>
                <tbody>
                    ${grn.items.map((item, idx) => `
                        <tr>
                            <td>${idx + 1}</td>
                            <td>${item.itemName}</td>
                            <td style="font-family: monospace; font-size: 11px;">${item.barcode}</td>
                            <td class="text-right">${item.costPrice.toLocaleString(undefined, {minimumFractionDigits: 2})}</td>
                            <td class="text-center"><b>${item.qty}</b></td>
                            <td class="text-right">${item.lineTotal.toLocaleString(undefined, {minimumFractionDigits: 2})}</td>
                        </tr>
                    `).join('')}
                </tbody>
            </table>
            <div class="text-right" style="margin-top: 8px; font-weight: bold; font-size: 14px;">
                GRN Sub Total: LKR ${grn.totalAmount.toLocaleString(undefined, {minimumFractionDigits: 2})}
            </div>
        </div>
      `).join('');

      // මුළු A4 පිටුවේම HTML එක
      const html = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>Purchase - ${purchase.invoiceNo}</title>
          <style>
            @page { size: A4; margin: 15mm; }
            body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px; color: #333; line-height: 1.5; }
            
            .header { text-align: center; margin-bottom: 25px; border-bottom: 2px solid #2563eb; padding-bottom: 15px; }
            .header h1 { margin: 0; font-size: 22px; text-transform: uppercase; color: #1e293b; letter-spacing: 1px; }
            .header p { margin: 5px 0 0 0; color: #64748b; font-size: 14px; }
            
            .info-section { display: flex; justify-content: space-between; margin-bottom: 30px; background: #f8fafc; padding: 15px; border-radius: 6px; border: 1px solid #e2e8f0; }
            .info-box { width: 48%; }
            .info-box p { margin: 6px 0; font-size: 13px; }
            
            .grn-section { margin-bottom: 30px; page-break-inside: avoid; }
            .grn-section h3 { margin: 0 0 10px 0; font-size: 14px; background: #e2e8f0; padding: 8px 12px; border-radius: 4px; color: #334155; }
            
            table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
            th, td { border: 1px solid #cbd5e1; padding: 8px 10px; text-align: left; }
            th { background-color: #f1f5f9; color: #475569; font-size: 11px; text-transform: uppercase; }
            
            .text-right { text-align: right; }
            .text-center { text-align: center; }
            
            .grand-total-box { float: right; width: 300px; background: #eff6ff; border: 1px solid #bfdbfe; padding: 15px; border-radius: 6px; margin-top: 10px; page-break-inside: avoid; }
            .grand-total-box .title { font-size: 12px; color: #3b82f6; font-weight: bold; text-transform: uppercase; margin-bottom: 5px; }
            .grand-total-box .amount { font-size: 20px; color: #1e3a8a; font-weight: bold; text-align: right; }
            
            .clearfix::after { content: ""; clear: both; display: table; }
            
            .signatures { display: flex; justify-content: space-between; margin-top: 80px; page-break-inside: avoid; }
            .sign-box { width: 28%; text-align: center; border-top: 1px dashed #94a3b8; padding-top: 10px; font-weight: bold; color: #64748b; font-size: 11px; text-transform: uppercase; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Goods Receipt Note / Purchase Summary</h1>
            <p>Generated by Store Management System</p>
          </div>

          <div class="info-section">
            <div class="info-box">
                <p><strong>Supplier:</strong> <span style="font-size: 15px; font-weight: bold; color: #0f172a;">${purchase.supplierName}</span></p>
                <p><strong>Invoice No:</strong> ${purchase.invoiceNo}</p>
            </div>
            <div class="info-box text-right">
                <p><strong>Date:</strong> ${new Date(purchase.createdAt).toLocaleString()}</p>
                <p><strong>System ID:</strong> #${purchase.purchaseId}</p>
            </div>
          </div>

          ${grnHTML}

          <div class="clearfix">
              <div class="grand-total-box">
                  <div class="title">Grand Total</div>
                  <div class="amount">LKR ${purchase.grandTotal.toLocaleString(undefined, {minimumFractionDigits: 2})}</div>
              </div>
          </div>

          <div class="signatures">
            <div class="sign-box">Prepared By<br><br>................................</div>
            <div class="sign-box">Checked By<br><br>................................</div>
            <div class="sign-box">Authorized By<br><br>................................</div>
          </div>
        </body>
        </html>
      `;

      doc.write(html);
      doc.close();

      setTimeout(() => {
        frame.contentWindow.focus();
        frame.contentWindow.print();
      }, 500);
    }
  }));

  return (
    <iframe
      ref={printFrameRef}
      style={{ display: 'none' }}
      title="A4 Print"
    />
  );
});

export default PurchaseA4Print;