/**
 * The contract between the server's pricing engine and the till's port of it.
 *
 * `promotion-corpus.json` is generated by the backend test suite from the canonical Java
 * engine. This runs the JS engine over every case and fails on any difference in the priced
 * result or the decision trace. A failure here means the two engines disagree, fix the
 * server first, regenerate the corpus, then bring this port in line.
 *
 *   npm run test:promotions
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { evaluateLine, evaluateOrder } from "../promotionEngine.js";

const here = dirname(fileURLToPath(import.meta.url));
const corpus = JSON.parse(readFileSync(join(here, "..", "promotion-corpus.json"), "utf8"));

const two = (value) => (value == null ? null : Number(Number(value).toFixed(2)));

const normaliseApplication = (application) => {
  const out = {};
  for (const [key, value] of Object.entries(application)) {
    out[key] = typeof value === "number" ? two(value) : value;
  }
  return out;
};

const normaliseDecisions = (decisions) =>
  (decisions || []).map((d) => ({
    promotionId: d.promotionId,
    promotionName: d.promotionName,
    outcome: d.outcome,
    discount: two(d.discount),
  }));

test(`promotion corpus v${corpus.version}: ${corpus.cases.length} cases`, () => {
  assert.ok(corpus.cases.length > 0, "corpus is empty");
});

for (const c of corpus.cases) {
  test(c.id, () => {
    const input = c.input;
    const result = c.kind === "line"
      ? evaluateLine(input.line, input.branchId, input.cartBaseSubtotal, input.promotions)
      : evaluateOrder(input.branchId, input.customerId, input.baseTotal, input.manualBillDiscount,
          input.pricedLines, input.linesHaveExclusive, input.promotions);

    assert.deepEqual(
      normaliseApplication(result.application),
      normaliseApplication(c.expected.application),
      `${c.id}: application differs`,
    );
    assert.deepEqual(
      normaliseDecisions(result.decisions),
      normaliseDecisions(c.expected.decisions),
      `${c.id}: decision trace differs`,
    );
  });
}
