export const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  CASHIER: 'CASHIER',
};

export const PERMISSIONS = {
  // POS
  ACCESS_POS: [ROLES.CASHIER, ROLES.MANAGER, ROLES.ADMIN],
  
  // Customers
  MANAGE_CUSTOMERS: [ROLES.CASHIER, ROLES.MANAGER, ROLES.ADMIN],
  
  // Items
  MANAGE_ITEMS: [ROLES.MANAGER, ROLES.ADMIN],
  VIEW_ITEMS: [ROLES.CASHIER, ROLES.MANAGER, ROLES.ADMIN],
  
  // Stock
  VIEW_STOCK: [ROLES.CASHIER, ROLES.MANAGER, ROLES.ADMIN],
  ADJUST_STOCK: [ROLES.MANAGER, ROLES.ADMIN],
  TRANSFER_STOCK: [ROLES.MANAGER, ROLES.ADMIN],
  
  // Reports
  VIEW_REPORTS: [ROLES.MANAGER, ROLES.ADMIN],
  VIEW_DASHBOARD: [ROLES.MANAGER, ROLES.ADMIN],
  
  // Shifts
  MANAGE_SHIFTS: [ROLES.CASHIER, ROLES.MANAGER, ROLES.ADMIN],
  
  // Expenses & Cash Drops
  RECORD_EXPENSES: [ROLES.CASHIER, ROLES.MANAGER, ROLES.ADMIN],
  
  // Branches
  MANAGE_BRANCHES: [ROLES.ADMIN],
  
  // Users
  MANAGE_USERS: [ROLES.ADMIN],
  
  // Cancel Orders
  CANCEL_ORDERS: [ROLES.MANAGER, ROLES.ADMIN],
};

export const hasPermission = (userRole, permission) => {
  return PERMISSIONS[permission]?.includes(userRole) || false;
};

export const canAccessAllBranches = (userRole) => {
  return userRole === ROLES.ADMIN;
};